app_bundle:
    resource: "@AppBundle/Controller/PointController.php"
    type: "annotation"
    prefix: "/api"

open_loyalty_core:
    resource: "@OpenLoyaltyCoreBundle/Resources/config/routing.yml"
